# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9748265a9b74fe765fa73ae7afe15b0900698e526e19cb9cc89723197ee1e9b6ec6459f46a1e9811bdd3e0490ac24d9a21a284ea74e8982e71e537edc630f812

test:
  secret_key_base: 7fc4ba3787076287040405ce0d4806dcc24f7f11f68cd2c1a00efb87797a0f659efccf8eb542da19b9fdf3fa1a4bf41e3dbfff2c92d92f8a75bc6bc6c0aaf0e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
